version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: players-liga
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
